### ISSUE TITLE
More consistent splitting

### ISSUE THREAD

**Issue by tomek-he-him** [stoeffel/reassemble-string#4]
At the moment here’s what we have:

``` js
const reassembleString = require('reassemble-string');
const pipify = reassembleString((a, b) => a + '|' + b); 

pipify('hello world');   //» 'hello|world'
pipify('hello-world');   //» 'hello|world'
pipify('hello_world');   //» 'hello|world'
pipify('hello.world');   //» 'hello|world'
pipify('helloWorld');    //» 'hello|World' – oops!
```

Would it be complicated to make this consistent?

``` js
pipify('helloWorld');    //» 'hello|world'
```

**Comment by tomek-he-him** [comment]
(Breaking change, BTW)

**Comment by stoeffel** [comment]
Hmm.. I think it is consistent see [test#L30](https://github.com/stoeffel/reassemble-string/blob/master/tests/test.js#L30).
I think `reassembleString` shouldn't change the previous and next string.
If a user wants to make your example work he can do:

``` js
const pipify = reassembleString((a, b) => a + '|' + b.toLowerCase()); 
```

**Comment by tomek-he-him** [comment]
I see it this way:

This is a generic, high-level tool. Its goal is to take a representation of a phrase in any convention and convert it to a specific convention. It doesn’t matter what the input is, I only care about the output.

So when I want to say `a specific phrase` in different conventions I’ll use `a_specific_phrase` in Python, `a-specific-phrase` in CSS and `aSpecificPhrase` in JavaScript. But I still have the same on my mind.

That was in English. Here’s the same translated to JS:

``` js
import reassembleString from 'reassemble-string';
const dashify = reassembleString((a, b) => a + '-' + b);
const underscorify = reassembleString((a, b) => a + '_' + b);
const spacify = reassembleString((a, b) => a + ' ' + b);
const camelize = reassembleString((a, b) => a + b.toUpperCase());

dashify(underscorify('a specific phrase'));  //» a-specific-phrase
dashify(spacify('a specific phrase'));       //» a-specific-phrase
dashify(camelize('a specific phrase'));      //» a-Specific-Phrase  – oops!
```

**Comment by tomek-he-him** [comment]
A better translation :)

``` js
import reassembleString from 'reassemble-string';
const iWrote = {
  inPython: reassembleString((a, b) => a + '_' + b),
  inCss: reassembleString((a, b) => a + '-' + b),
  inJs: reassembleString((a, b) => a + b.toUpperCase()),
};
const iMeant = reassembleString((a, b) => a + ' ' + b);

iMeant(iWrote.inPython('a phrase'));  //» a phrase
iMeant(iWrote.inCss('a phrase'));     //» a phrase
iMeant(iWrote.inJs('a phrase'));      //» a Phrase  – oops!
```

**Comment by stoeffel** [comment]
> A better translation :)

Yop, I know what you mean. 
But I think this behaviour is predictable since it is exactly what you did. 1. `iWrote` then `iMeant`
You could still lowercase `b` in `iMeant` if you want an other behaviour.
If we change the behaviour of `reassemble-string` so b is always lowercased it would be immpossible to know what the original character was. But with the current implementation you can (`This is a generic, high-level tool`:smiley:)

`reassemble-string` justs splits at `-_\s` and `aA` and gives the last character of the previous word and the first of the next word.

**Comment by tomek-he-him** [comment]
> it would be immpossible to know what the original character was

Just as it’s now impossible to know what the separator within `a-b` was. Semantically `a-b`, `a_b`, `a b` and `aB` are the same. In the last case the change of case is the kind’a separator.

But – fair enough. Both approaches have their pros and cons. I just found the current behavior counter-intuitive. But perhaps it’s more intuitive for others.

Feel free to close this issue if you still don’t agree @stoeffel :)

**Comment by stoeffel** [comment]
> Just as it’s now impossible to know what the separator within a-b was. Semantically a-b, a_b, a b and aB are the same

Agrred.

> I just found the current behavior counter-intuitive

hmm... maybe you are right.

I don't feel that strong about the current behaviour, so let's go for it :rocket: 

btw: I added you as a collaborator :octocat:

**Comment by tomek-he-him** [comment]
I’m glad I’ve convinced you :)

Thanks :) I won’t have time to touch the thing until tomorrow though.

**Comment by stoeffel** [comment]
> Thanks :) I won’t have time to touch the thing until tomorrow though.

Np. No need to hurry. :smiley:

**Comment by stoeffel** [comment]
> I won’t have time to touch the thing until tomorrow though

I was quicker :smile:

**Comment by tomek-he-him** [comment]
:D Sorry, I’ve had lots of unexpected work over the last couple of days. Thanks again!
